### ISSUE TITLE
Loading adventure with a patron not working

### ISSUE THREAD

**Issue by Fmagdi** [dhusemann/idlecombos#11]
Hello

Thank you for your work first of all, it comes incredibly in handy.

I have been using the Load New Adventure feature with no issues for patron ID 0 (without patron) and it always worked without issues.

However when trying to load an adventure and choosing a patron ID other than 0, I get the message that the adventure has been loaded successfully, but the "Current Adventure" for the active adventure in the Adventures tab still shows -1 instead of the chosen adventure. I tried starting the requested adventure from the game to make sure it can be started and it did, but still not from the "Load New Adventure" feature. 

Same result was true for different adventures in different campaigns and with different patrons, any patron ID other than 0 reports success but doesn't actually load the adventure.
The adventure I first encountered the issue with was 814, repeated for others as well for all patrons > 0.

![2022-05-30 (1)](https://user-images.githubusercontent.com/61050730/170993070-fcdd9bf9-9a97-49ba-968c-a7f606bc5393.png)

Another smaller related issue, the patron entry box doesn't accept 4 (Zariel). Modifying the following line in LoadAdventure() fixed the Zariel issue:
if !((patrontoload > -1) && (patrontoload < 4))    -> if !((patrontoload > -1) && (patrontoload < 5))

**Comment by dhusemann** [comment]
probably broke with the 4th party. since that code is almost the same as the trying to add 4th party for display. as my health lets me will try to resolve

**Comment by Fmagdi** [comment]
Thank you.
Wish I could help but I'm still figuring out the code especially the server interactions. If you have any resources or references as to how the server calls work or are formulated, I could try to be of assistance.

**Comment by dhusemann** [comment]
issue on CNE side. closeing as unresolvable.
